<a href="https://colab.research.google.com/github/afafrafat77/COVID-19-data-analysis/blob/main/COVID_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import necessary libraries

In [622]:
import pandas as pd

# Load the datasets

In [623]:
covid_complete_df =pd.read_csv("/content/covid_19_clean_complete.csv")
country_wise_df=pd.read_csv("/content/country_wise_latest.csv")

# Displaying and Cleaning covid_complete_df

In [624]:
covid_complete_df.head(10)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa
5,NaN,Antigua and Barbuda,17.06080,-61.796400,2020-01-22,0,0,0,0,Americas
6,NaN,Argentina,-38.41610,-63.616700,2020-01-22,0,0,0,0,Americas
7,NaN,Armenia,40.06910,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.47350,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.86880,151.209300,2020-01-22,0,0,0,0,Western Pacific

In [625]:
covid_complete_df .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [626]:
covid_complete_df .describe()

,Lat,Long,Confirmed,Deaths,Recovered,Active
count,49068.000000,49068.000000,4.906800e+04,49068.000000,4.906800e+04,4.906800e+04
mean,21.433730,23.528236,1.688490e+04,884.179160,7.915713e+03,8.085012e+03
std,24.950320,70.442740,1.273002e+05,6313.584411,5.480092e+04,7.625890e+04
min,-51.796300,-135.000000,0.000000e+00,0.000000,0.000000e+00,-1.400000e+01
25%,7.873054,-15.310100,4.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,23.634500,21.745300,1.680000e+02,2.000000,2.900000e+01,2.600000e+01
75%,41.204380,80.771797,1.518250e+03,30.000000,6.660000e+02,6.060000e+02
max,71.706900,178.065000,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06

In [627]:
covid_complete_df .shape

(49068, 10)

In [628]:
covid_complete_df .drop(columns=['Lat','Long'],inplace=True)

In [629]:
covid_complete_df .isnull().sum()

Province/State    34404
Country/Region        0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
Active                0
WHO Region            0
dtype: int64

In [630]:
covid_complete_df ['Province/State'].unique()

array([nan, 'Australian Capital Territory', 'New South Wales',
       'Northern Territory', 'Queensland', 'South Australia', 'Tasmania',
       'Victoria', 'Western Australia', 'Alberta', 'British Columbia',
       'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
       'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec',
       'Saskatchewan', 'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu',
       'Guangdong', 'Guangxi', 'Guizhou', 'Hainan', 'Hebei',
       'Heilongjiang', 'Henan', 'Hong Kong', 'Hubei', 'Hunan',
       'Inner Mongolia', 'Jiangsu', 'Jiangxi', 'Jilin', 'Liaoning',
       'Macau', 'Ningxia', 'Qinghai', 'Shaanxi', 'Shandong', 'Shanghai',
       'Shanxi', 'Sichuan', 'Tianjin', 'Tibet', 'Xinjiang', 'Yunnan',
       'Zhejiang', 'Faroe Islands', 'Greenland', 'French Guiana',
       'French Polynesia', 'Guadeloupe', 'Mayotte', 'New Caledonia',
       'Reunion', 'Saint Barthelemy', 'St Martin', 'Martinique', 'Aruba',
       'Curacao', 'Sint Maarten', 'Bermuda', 'Cayman Islands',
       'Channel Islands', 'Gibraltar', 'Isle of Man', 'Montserrat',
       'Northwest Territories', 'Yukon', 'Anguilla',
       'British Virgin Islands', 'Turks and Caicos Islands',
       'Falkland Islands (Malvinas)', 'Saint Pierre and Miquelon'],
      dtype=object)

In [631]:
#Too many null values better to drop the whole column
covid_complete_df .drop(columns='Province/State',inplace=True)

In [632]:
covid_complete_df ['Date'] = pd.to_datetime(covid_complete_df['Date'])

In [633]:
covid_complete_df .rename(columns={'Country/Region':'Country'},inplace=True)

In [634]:
covid_complete_df

,Country,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Albania,2020-01-22,0,0,0,0,Europe
2,Algeria,2020-01-22,0,0,0,0,Africa
3,Andorra,2020-01-22,0,0,0,0,Europe
4,Angola,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...
49063,Sao Tome and Principe,2020-07-27,865,14,734,117,Africa
49064,Yemen,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,Comoros,2020-07-27,354,7,328,19,Africa
49066,Tajikistan,2020-07-27,7235,60,6028,1147,Europe
49067,Lesotho,2020-07-27,505,12,128,365,Africa

## Displaying and Cleaning country_wise_df

In [635]:
country_wise_df.head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe

In [636]:
country_wise_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [637]:
country_wise_df.drop(columns=['Deaths / 100 Recovered', 'Confirmed last week', '1 week change'],inplace=True)

In [638]:
country_wise_df.rename(columns = {'Country/Region': 'Country', 'Deaths / 100 Cases': 'Deaths_Rate','Recovered / 100 Cases': 'Recovered_Rate','1 week % increase': 'Weekly_Increase_Percentage'}, inplace = True)

In [639]:
country_wise_df

,Country,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa

In [640]:
country_wise_df.describe()

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage
count,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000
mean,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,3.019519,64.820535,13.606203
std,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.454302,26.287694,24.509838
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,-3.840000
25%,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,0.945000,48.770000,2.775000
50%,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,2.150000,71.320000,6.890000
75%,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.875000,86.885000,16.855000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,28.560000,100.000000,226.320000

In [641]:
country_wise_df.isnull().sum()

Country                       0
Confirmed                     0
Deaths                        0
Recovered                     0
Active                        0
New cases                     0
New deaths                    0
New recovered                 0
Deaths_Rate                   0
Recovered_Rate                0
Weekly_Increase_Percentage    0
WHO Region                    0
dtype: int64

# Merge the two dataframes

In [642]:
merged_df = country_wise_df.merge(covid_complete_df, on='Country', how='inner')
merged_df

,Country,Confirmed_x,Deaths_x,Recovered_x,Active_x,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage,WHO Region_x,Date,Confirmed_y,Deaths_y,Recovered_y,Active_y,WHO Region_y
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-23,0,0,0,0,Eastern Mediterranean
2,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-24,0,0,0,0,Eastern Mediterranean
3,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-25,0,0,0,0,Eastern Mediterranean
4,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-26,0,0,0,0,Eastern Mediterranean
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49063,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa,2020-07-23,2124,28,510,1586,Africa
49064,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa,2020-07-24,2296,32,514,1750,Africa
49065,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa,2020-07-25,2434,34,518,1882,Africa
49066,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa,2020-07-26,2512,34,518,1960,Africa
49067,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,57.85,Africa,2020-07-27,2704,36,542,2126,Africa

In [643]:
# Calculate average values for Confirmed, Deaths, Recovered, and Active cases
merged_df['Confirmed'] = (merged_df['Confirmed_x'] + merged_df['Confirmed_y']) / 2
merged_df['Deaths'] = (merged_df['Deaths_x'] + merged_df['Deaths_y']) / 2
merged_df['Recovered'] = (merged_df['Recovered_x'] + merged_df['Recovered_y']) / 2
merged_df['Active'] = (merged_df['Active_x'] + merged_df['Active_y']) / 2

# Drop redundant columns
merged_df.drop(columns=['Confirmed_x', 'Deaths_x', 'Recovered_x', 'Active_x', 'Confirmed_y', 'Deaths_y', 'Recovered_y', 'Active_y'], inplace=True)
merged_df.drop_duplicates(inplace=True)
merged_df.drop(columns=['WHO Region_y'], inplace=True)
merged_df.rename(columns={'WHO Region_x': 'WHO Region'}, inplace=True)
merged_df

,Country,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage,WHO Region,Date,Confirmed,Deaths,Recovered,Active
0,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-22,18131.5,634.5,12599.0,4898.0
1,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-23,18131.5,634.5,12599.0,4898.0
2,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-24,18131.5,634.5,12599.0,4898.0
3,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-25,18131.5,634.5,12599.0,4898.0
4,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-26,18131.5,634.5,12599.0,4898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49063,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-23,2414.0,32.0,526.0,1856.0
49064,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-24,2500.0,34.0,528.0,1938.0
49065,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-25,2569.0,35.0,530.0,2004.0
49066,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-26,2608.0,35.0,530.0,2043.0
49067,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-27,2704.0,36.0,542.0,2126.0

In [644]:
merged_df.dtypes

Country                               object
New cases                              int64
New deaths                             int64
New recovered                          int64
Deaths_Rate                          float64
Recovered_Rate                       float64
Weekly_Increase_Percentage           float64
WHO Region                            object
Date                          datetime64[ns]
Confirmed                            float64
Deaths                               float64
Recovered                            float64
Active                               float64
dtype: object

In [645]:
merged_df['WHO Region'] = merged_df['WHO Region'].astype('category')
merged_df

,Country,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage,WHO Region,Date,Confirmed,Deaths,Recovered,Active
0,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-22,18131.5,634.5,12599.0,4898.0
1,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-23,18131.5,634.5,12599.0,4898.0
2,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-24,18131.5,634.5,12599.0,4898.0
3,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-25,18131.5,634.5,12599.0,4898.0
4,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-26,18131.5,634.5,12599.0,4898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49063,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-23,2414.0,32.0,526.0,1856.0
49064,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-24,2500.0,34.0,528.0,1938.0
49065,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-25,2569.0,35.0,530.0,2004.0
49066,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-26,2608.0,35.0,530.0,2043.0
49067,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-27,2704.0,36.0,542.0,2126.0

In [646]:
# Retain rows where 'Confirmed' is between 10 and 1 million
merged_df = merged_df[(merged_df['Confirmed'] >= 10) & (merged_df['Confirmed'] < 1000000)]

In [647]:
merged_df.drop_duplicates(inplace=True)
merged_df

<ipython-input-647-7a84123cd6a4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.drop_duplicates(inplace=True)

,Country,New cases,New deaths,New recovered,Deaths_Rate,Recovered_Rate,Weekly_Increase_Percentage,WHO Region,Date,Confirmed,Deaths,Recovered,Active
0,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-22,18131.5,634.5,12599.0,4898.0
1,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-23,18131.5,634.5,12599.0,4898.0
2,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-24,18131.5,634.5,12599.0,4898.0
3,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-25,18131.5,634.5,12599.0,4898.0
4,Afghanistan,106,10,18,3.50,69.49,2.07,Eastern Mediterranean,2020-01-26,18131.5,634.5,12599.0,4898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49063,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-23,2414.0,32.0,526.0,1856.0
49064,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-24,2500.0,34.0,528.0,1938.0
49065,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-25,2569.0,35.0,530.0,2004.0
49066,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-26,2608.0,35.0,530.0,2043.0
49067,Zimbabwe,192,2,24,1.33,20.04,57.85,Africa,2020-07-27,2704.0,36.0,542.0,2126.0

In [648]:
country_data =merged_df .groupby('Country')[['Confirmed', 'Deaths', 'Recovered']].sum()
country_data

                    Confirmed    Deaths  Recovered
Country
Afghanistan         4376917.0  143835.0  2767732.0
Albania              557071.0   16390.0   317468.5
Algeria             3219339.5  148308.0  2148626.5
Andorra              132460.0    7599.5   110019.0
Angola               100631.0    4393.0    26034.5
...                       ...       ...        ...
West Bank and Gaza  1115104.5    8017.0   383250.0
Western Sahara          360.0      36.0      288.0
Yemen                192544.0   54255.5    90191.5
Zambia               492598.5   14481.5   306415.5
Zimbabwe             279573.0    3824.5    57051.5

[185 rows x 3 columns]

In [649]:
daily_data = merged_df .groupby('Date')[['Confirmed', 'Deaths', 'Recovered']].sum()
daily_data

             Confirmed    Deaths  Recovered
Date
2020-01-22   5308068.5  232491.5  3542147.0
2020-01-23   5525061.0  244132.0  3739320.5
2020-01-24   5852333.5  270882.0  3977102.0
2020-01-25   6199729.5  289514.0  4292579.5
2020-01-26   6186794.5  289504.0  4223028.0
...                ...       ...        ...
2020-07-23  12861837.5  893795.0  6906650.5
2020-07-24  12913158.5  895345.5  6954279.0
2020-07-25  12957832.5  896370.0  6990760.0
2020-07-26  12995379.5  897554.0  7019121.5
2020-07-27  13047685.5  899098.0  7058799.5

[188 rows x 3 columns]